name: abms
channels: [conda-forge, defaults]
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - pyarrow
  - lightgbm
  - transformers>=4.52
  - datasets>=2.18
  - evaluate>=0.4
  - accelerate>=0.27
  - streamlit
  - spacy>=3.0
  - nltk
  - pip
  - pip:
    - empath
    - pycryptodome
    - textstat
    - spacy-transformers
